apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modelisation
  name: modelisation
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modelisation
  template:
    metadata:
      labels:
        app: modelisation
    spec:
      containers:
      - image: mxsamak/modelisationclean:latest
        name: modelisation
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
